# Generated by Django 3.2.7 on 2021-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_status_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_sold_for',
            field=models.IntegerField(default=0),
        ),
    ]
