# Generated by Django 3.2.7 on 2021-09-27 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_price_sold_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HOME', 'Home'), ('SP', 'Sports'), ('ELC', 'Electronics'), ('FOOD', 'Food'), ('CAR', 'Car'), ('BOOK', 'Books')], default='HOME', max_length=4),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_sold_for',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
