# Generated by Django 3.2.7 on 2022-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211213_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, default='media/images/beta-climbing-designs-evo-sport-super-standard-clipstick_tTdVh9U.jpeg', null=True, upload_to='images/'),
        ),
    ]
